# Default values for argo-workflows

# Application values for ArgoCD
application:
  name: workflow-app
  namespace: argocd
  project: default
  repoURL: https://github.com/segfault16/python-multistage-docker
  targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

# Workflow Template values
workflowTemplate:
  name: python-multistage-docker
  serviceAccountName: argo-workflow-sa
  volumeClaimSize: 64Mi
  repo:
    url: https://github.com/segfault16/python-multistage-docker
    branch: master
  images:
    prefix: 494150080395.dkr.ecr.eu-west-1.amazonaws.com
    repository: mega-repository
    cacheTag: mega-repository-cache

# Workflow values
workflow:
  generateName: python-multistage-docker-
  serviceAccountName: argo-workflow-sa
  appRevision: latest # This will be overridden by ArgoCD
